### ISSUE TITLE
basic metrics

### ISSUE THREAD

**Issue by goern** [thoth-station/package-releases-job#12]
Implement metric to figure out how many packages per run have been added to the database, should be smaller than 40 (as pypi index only keeps the most current 40). If more than 40 then alarm to reset the scheduling interval to something smaller than current scheduling interval.

see also https://trello.com/c/4Ymy30Dk

**Comment by durandom** [comment]
see https://github.com/thoth-station/package-releases-job/pull/13

**Comment by durandom** [comment]
done via https://github.com/thoth-station/package-releases-job/pull/13
