### ISSUE TITLE
Add monitoring of Kebechet

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-releases-job#28]
As Kebechet bot I want to know about new releases of myself so I'm always automatically up2date based on releases on PyPI.

We already have configuration to monitor packages for releases in the conf directory. Let's extend ansible playbooks and configmap with a URL to webhook (supplied by env variables) that can be triggered directly by package releases job on kebechet update on PyPI. This way each time we make a new release of kebechet, package releases job detects this update, triggers openshift build webhook in kebechet deployment (the AICoE bots namespace) and kebechet gets updated).

**Comment by goern** [comment]
Please turn this into a Trello card

**Comment by fridex** [comment]
It's already present - https://trello.com/c/RKyCP8bl/212-automatically-update-kebechet-from-package-releases-job
