### ISSUE TITLE
Use PROMETHEUS_PUSHGATEWAY_HOST and PROMETHEUS_PUSHGATEWAY_HOST

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-releases-job#29]
The Prometheus configuration now uses host and port environment variables [1]. Let's use these variables from configmap correctly so the configuration is propagated. The current implementation always defaults to "pushgateway:9091" which is not nice (metrics reporting might be omitted in some deployments).

[1] https://github.com/thoth-station/core/blob/master/openshift/configmap-template.yaml#L46

**Comment by goern** [comment]
https://trello.com/c/EU862mnO

**Comment by goern** [comment]
too much overhead... a trello-github:issue integration would be nice to have.
