### ISSUE TITLE
document how to use THOTH_PACKAGE_RELEASES_VERBOSE

### ISSUE THREAD

**Issue by goern** [thoth-station/package-releases-job#38]
I want to enable verbose logging for the cronjob, how to do it using THOTH_PACKAGE_RELEASES_VERBOSE?

**Comment by fridex** [comment]
You can set environment variable ``THOTH_LOG_PACKAGE_RELEASES`` to ``DEBUG`` to increase verbosity. This is handled by our [common logging](http://thoth-station.ninja/docs/thoth.common.html#thoth.common.logging.init_logging).
